# Scheduled wrapper for scripts/brief.py — a narrative briefing generated by a
# read-only headless Claude run and delivered via Telegram (2026-09-06).
# ASCII-only on purpose (PS 5.1 safe without BOM).
#
#   pwsh scripts/brief.ps1 -Kind paper8w
param([Parameter(Mandatory=$true)][string]$Kind)

$ErrorActionPreference = "Continue"
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}
$env:PYTHONIOENCODING = "utf-8"
# Task Scheduler PATH may miss ~/.local/bin where claude.exe lives
$env:PATH = "$env:USERPROFILE\.local\bin;$env:APPDATA\npm;$env:PATH"

$logPath = Join-Path $PSScriptRoot "..\..\stock-investing\brief-log.txt"
try {
    if ((Test-Path $logPath) -and ((Get-Item $logPath).Length -gt 200KB)) {
        Get-Content $logPath -Tail 500 | Set-Content $logPath -Encoding utf8
    }
    Start-Transcript -Path $logPath -Append | Out-Null
} catch {}

$py = Join-Path $PSScriptRoot "..\.venv\Scripts\python.exe"
if (-not (Test-Path $py)) { $py = "python" }

Write-Host "=== BRIEF ($Kind) $(Get-Date -Format s) ===" -ForegroundColor Cyan
& $py (Join-Path $PSScriptRoot "brief.py") --kind $Kind 2>&1 | Out-Host
$rc = $LASTEXITCODE

try { Stop-Transcript | Out-Null } catch {}
exit $rc
